# docker-compose.yml
version: "3.9"
services:
  worker:
    container_name: worker
    build:
      context: worker
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - queue
    environment:
      REDIS_HOST: queue
      REDIS_PORT: 6379
      REDIS_PASSWORD: ChangeMe
  queue:
    container_name: queue
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ChangeMe
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
